version: "3.8"

services:
  duta-energi-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dem
    restart: always
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
