name: Deploy ke Synology NAS

on:
  push:
    branches: [master]

# Mengatasi peringatan Node.js 20 dengan memaksa penggunaan Node.js 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restart NextJS Container
        run: |
          cd /workspace
          # Menambahkan '|| true' sementara untuk melihat apakah ada kendala permission
          docker compose down || true
          docker compose up -d --build
